### ISSUE TITLE
RSS classes missing from source

### ISSUE THREAD

**Issue by WillStrohl** [redtempo/dnnstuff.aggregator#2]
If you try to build the solution in Release mode, you get several errors about undefined classes, including:

* RssItem
* RssDocument
* Several RegularExpression members

I'm guessing that those files were never included in any previous check-in.  Often times I see that happen due to the local or global gitignore having unexpected exclusions.

Steps to Reproduce this Issue:

1. Clone the repository to a new (empty) folder.
2. Update the build location to be in a local folder (no one else will have your .../sites/Dnn7 folder path).
3. Update the SaveServerSettingsInUserFile setting in the project file to be True (for the same reason as #2).
4. Open the solution in Visual Studio 2017.
5. Build the solution in Debug mode.  (Surprisingly no issues the first time.)
6. Build the solution in Release mode.

Expected Behavior:
The module solution builds and the resulting DLL's are placed in a local folder.

Actual Behavior:
There are several errors about unknown types and the solution can't finish building.

**Comment by richard-edwards** [comment]
Appreciate the well done bug report Will, thanks. Looks like it's not picking up dll's from the refs folder for some reason. I'm sure I checked this all out before pushing this up here but I'll check this out and the other issues you posted today in the next while.

In reference to #2, the hard coded build location for debug. I typically build to the bin folder of my dnn dev build, do you not do the same thing? I can build to a local folder of course but how do you set this up on your builds. If I build to local I then have to copy the dll's to my dev bin and attach the debuger. What's your favored or the accepted approach to this?

**Comment by WillStrohl** [comment]
I think many of us build from a module folder into a dev site.  You just have your path hard-coded.  None of us will have a path matching yours.  Also, many people won't know how to figure out where that path is.  Ideally, that path should be in the ModuleSpecific.targets file or somewhere similar.
